Repository magicbell-io/magicbell-js, pull requests merged in 2023-04, with the labels that each got.

#65 feat: add support for nested resources (#65
  packages/codegen/src/openapi.ts
  packages/magicbell/scripts/generate-resources.ts
Labels: enhancement, chore

#73 docs: use correct example for `useBell` with a specific store
  .changeset/clean-tigers-destroy.md
  packages/react-headless/README.md
Labels: documentation

#75 fix: handle network level request errors (#75
  .changeset/brown-stingrays-guess.md
  packages/magicbell/src/client.ts
Labels: bug

#81 chore: show type errors during build (#81
  scripts/vite/plugins/writeTypeDefs.js
Labels: chore

#82 feat: support allOf in schema to combine types (#82
  packages/codegen/package.json
  packages/codegen/src/openapi.ts
  packages/codegen/src/schema.ts
  packages/magicbell/src/schemas/imports.ts
  packages/magicbell/src/schemas/notifications.ts
  packages/magicbell/src/schemas/push-subscriptions.ts
  packages/magicbell/src/schemas/subscriptions.ts
  packages/magicbell/src/schemas/users.ts
  yarn.lock
Labels: enhancement

#107 fix: use accent color for dialog buttons
  .changeset/six-boxes-change.md
  packages/react/src/components/EnablePushNotificationsBanner/EnablePushNotificationsBanner.tsx
Labels: bug
